import { RadStation } from "./rad-station";
import { Dictionary } from "lodash";

export class RadStationList {

  static radStationList: RadStation[] = [
    {name:'Aberdeen, SD', value:'KABR'},
    {name:'Albany, NY', value:'KENX'},
    {name:'Albuquerque, NM', value:'KABX'},
    {name:'Amarillo, TX', value:'KAMA'},
    {name:'Anchorage/Kenai, AK', value:'PAHG'},
    {name:'Andersen AFB, Guam', value:'PGUA'},
    {name:'Atlanta, GA', value:'KFFC'},
    {name:'Beale AFB, CA', value:'KBBX'},
    {name:'Bethel, AK', value:'PABC'},
    {name:'Billings, MT', value:'KBLX'},
    {name:'Binghamton, NY', value:'KBGM'},
    {name:'Biorka Island/Sitka, AK', value:'PACG'},
    {name:'Birmingham, AL', value:'KBMX'},
    {name:'Bismarck, ND', value:'KBIS'},
    {name:'Blacksburg, VA', value:'KFCX'},
    {name:'Boise, ID', value:'KCBX'},
    {name:'Boston, MA', value:'KBOX'},
    {name:'Brownsville, TX', value:'KBRO'},
    {name:'Buffalo, NY', value:'KBUF'},
    {name:'Burlington, VT', value:'KCXX'},
    {name:'Camp Humphreys, KO', value:'RKSG'},
    {name:'Cannon AFB, NM', value:'KFDX'},
    {name:'Caribou, ME', value:'KCBW'},
    {name:'Cedar City, UT', value:'KICX'},
    {name:'Central Texas/Ft Hood, TX', value:'KGRK'},
    {name:'Charleston, SC', value:'KCLX'},
    {name:'Charleston, WV', value:'KRLX'},
    {name:'Cheyenne, WY', value:'KCYS'},
    {name:'Chicago, IL', value:'KLOT'},
    {name:'Cincinnati/Wilmington, OH', value:'KILN'},
    {name:'Cleveland, OH', value:'KCLE'},
    {name:'Columbia, SC', value:'KCAE'},
    {name:'Columbus AFB, MS', value:'KGWX'},
    {name:'Corpus Christi, TX', value:'KCRP'},
    {name:'Denver, CO', value:'KFTG'},
    {name:'Des Moines, IA', value:'KDMX'},
    {name:'Detroit, MI', value:'KDTX'},
    {name:'Dodge City, KS', value:'KDDC'},
    {name:'Dover AFB, DE', value:'KDOX'},
    {name:'Duluth, MN', value:'KDLH'},
    {name:'Dyess AFB, TX', value:'KDYX'},
    {name:'Edwards AFB, CA', value:'KEYX'},
    {name:'El Paso, TX', value:'KEPZ'},
    {name:'Elko, NV', value:'KLRX'},
    {name:'Eureka, CA', value:'KBHX'},
    {name:'Evansville, IN', value:'KVWX'},
    {name:'Fairbanks/Pedro Dome, AK', value:'PAPD'},
    {name:'Flagstaff, AZ', value:'KFSX'},
    {name:'Fort Smith, AR', value:'KSRX'},
    {name:'Frederick/Altus AFB, OK', value:'KFDR'},
    {name:'Ft Campbell, KY', value:'KHPX'},
    {name:'Ft Polk, LA', value:'KPOE'},
    {name:'Ft Rucker, AL', value:'KEOX'},
    {name:'Ft Worth, TX', value:'KFWS'},
    {name:'Gaylord, MI', value:'KAPX'},
    {name:'Glasgow, MT', value:'KGGW'},
    {name:'Goodland, KS', value:'KGLD'},
    {name:'Grand Forks, ND', value:'KMVX'},
    {name:'Grand Junction, CO', value:'KGJX'},
    {name:'Grand Rapids, MI', value:'KGRR'},
    {name:'Great Falls, MT', value:'KTFX'},
    {name:'Green Bay, WI', value:'KGRB'},
    {name:'Greer, SC', value:'KGSP'},
    {name:'Hastings, NE', value:'KUEX'},
    {name:'Holloman AFB, NM', value:'KHDX'},
    {name:'Houston, TX', value:'KHGX'},
    {name:'Huntsville/Hytop, AL', value:'KHTX'},
    {name:'Indianapolis, IN', value:'KIND'},
    {name:'Jackson, KY', value:'KJKL'},
    {name:'Jackson, MS', value:'KDGX'},
    {name:'Jacksonville, FL', value:'KJAX'},
    {name:'Kadena, JP', value:'RODN'},
    {name:'Kamuela/Kohala, HI', value:'PHKM'},
    {name:'Kansas City, MO', value:'KEAX'},
    {name:'Key West, FL', value:'KBYX'},
    {name:'King Salmon, AK', value:'PAKC'},
    {name:'Knoxville/Morristown, TN', value:'KMRX'},
    {name:'Kunsan, KO', value:'RKJK'}
  ];

  static getStationName:Dictionary<string> = {
    'KABR':'Aberdeen, SD',
    'KENX':'Albany, NY',
    'KABX':'Albuquerque, NM',
    'KAMA':'Amarillo, TX',
    'PAHG':'Anchorage/Kenai, AK',
    'PGUA':'Andersen AFB, Guam',
    'KFFC':'Atlanta, GA',
    'KBBX':'Beale AFB, CA',
    'PABC':'Bethel, AK',
    'KBLX':'Billings, MT',
    'KBGM':'Binghamton, NY',
    'PACG':'Biorka Island/Sitka, AK',
    'KBMX':'Birmingham, AL',
    'KBIS':'Bismarck, ND',
    'KFCX':'Blacksburg, VA',
    'KCBX':'Boise, ID',
    'KBOX':'Boston, MA',
    'KBRO':'Brownsville, TX',
    'KBUF':'Buffalo, NY',
    'KCXX':'Burlington, VT',
    'RKSG':'Camp Humphreys, KO',
    'KFDX':'Cannon AFB, NM',
    'KCBW':'Caribou, ME',
    'KICX':'Cedar City, UT',
    'KGRK':'Central Texas/Ft Hood, TX',
    'KCLX':'Charleston, SC',
    'KRLX':'Charleston, WV',
    'KCYS':'Cheyenne, WY',
    'KLOT':'Chicago, IL',
    'KILN':'Cincinnati/Wilmington, OH',
    'KCLE':'Cleveland, OH',
    'KCAE':'Columbia, SC',
    'KGWX':'Columbus AFB, MS',
    'KCRP':'Corpus Christi, TX',
    'KFTG':'Denver, CO',
    'KDMX':'Des Moines, IA',
    'KDTX':'Detroit, MI',
    'KDDC':'Dodge City, KS',
    'KDOX':'Dover AFB, DE',
    'KDLH':'Duluth, MN',
    'KDYX':'Dyess AFB, TX',
    'KEYX':'Edwards AFB, CA',
    'KEPZ':'El Paso, TX',
    'KLRX':'Elko, NV',
    'KBHX':'Eureka, CA',
    'KVWX':'Evansville, IN',
    'PAPD':'Fairbanks/Pedro Dome, AK',
    'KFSX':'Flagstaff, AZ',
    'KSRX':'Fort Smith, AR',
    'KFDR':'Frederick/Altus AFB, OK',
    'KHPX':'Ft Campbell, KY',
    'KPOE':'Ft Polk, LA',
    'KEOX':'Ft Rucker, AL',
    'KFWS':'Ft Worth, TX',
    'KAPX':'Gaylord, MI',
    'KGGW':'Glasgow, MT',
    'KGLD':'Goodland, KS',
    'KMVX':'Grand Forks, ND',
    'KGJX':'Grand Junction, CO',
    'KGRR':'Grand Rapids, MI',
    'KTFX':'Great Falls, MT',
    'KGRB':'Green Bay, WI',
    'KGSP':'Greer, SC',
    'KUEX':'Hastings, NE',
    'KHDX':'Holloman AFB, NM',
    'KHGX':'Houston, TX',
    'KHTX':'Huntsville/Hytop, AL',
    'KIND':'Indianapolis, IN',
    'KJKL':'Jackson, KY',
    'KDGX':'Jackson, MS',
    'KJAX':'Jacksonville, FL',
    'RODN':'Kadena, JP',
    'PHKM':'Kamuela/Kohala, HI',
    'KEAX':'Kansas City, MO',
    'KBYX':'Key West, FL',
    'PAKC':'King Salmon, AK',
    'KMRX':'Knoxville/Morristown, TN',
    'RKJK':'Kunsan, KO'
  }

}
